/**
 * selector.ts — Stable CSS selector generation for interactive elements.
 * Exported as a pure function so it is testable in isolation.
 */

/**
 * Build the most stable CSS selector we can for an element.
 *
 * Priority order:
 *   1. data-* attributes (most app-specific, very stable)
 *   2. name attribute (forms)
 *   3. aria-label attribute
 *   4. id attribute
 *   5. nth-child path fallback (least stable but always works)
 */
export function getStableSelector(el: Element): string {
  const tag = el.tagName.toLowerCase();

  // 1. data-* attributes — prefer data-field, data-id, data-testid, data-cy, data-qa
  const dataAttrs = ["data-field", "data-id", "data-testid", "data-cy", "data-qa", "data-key"];
  for (const attr of dataAttrs) {
    const val = el.getAttribute(attr);
    if (val) return `${tag}[${attr}="${CSS.escape(val)}"]`;
  }

  // 2. name attribute
  const name = el.getAttribute("name");
  if (name) return `${tag}[name="${CSS.escape(name)}"]`;

  // 3. aria-label attribute
  const ariaLabel = el.getAttribute("aria-label");
  if (ariaLabel) return `${tag}[aria-label="${CSS.escape(ariaLabel)}"]`;

  // 4. id attribute (only if the id looks stable — not auto-generated)
  const id = el.id;
  if (id && !isAutoGeneratedId(id)) return `#${CSS.escape(id)}`;

  // 5. nth-child path (walk up the tree building a minimal path)
  return buildNthChildPath(el);
}

/** Heuristic: auto-generated IDs typically contain digits or GUIDs after a prefix */
function isAutoGeneratedId(id: string): boolean {
  // React / Angular generated IDs like "mat-input-3", "ng-select-0"
  // or random GUIDs like "abb3f21c-..."
  return /[\d]{2,}/.test(id) || /^[a-f0-9]{8}-/.test(id);
}

/**
 * Build a path like "div:nth-of-type(2) > form > button:nth-of-type(1)".
 * Walks up a maximum of 5 levels to keep selectors short.
 */
function buildNthChildPath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;
  let depth = 0;
  const MAX_DEPTH = 5;

  while (current && depth < MAX_DEPTH) {
    const part = getNthChildSegment(current);
    parts.unshift(part);

    // Stop early if we hit a stable anchor
    const anchorAttr = current.id && !isAutoGeneratedId(current.id)
      ? `#${CSS.escape(current.id)}`
      : null;
    if (anchorAttr && depth > 0) {
      parts[0] = anchorAttr;
      break;
    }

    current = current.parentElement;
    depth++;
  }

  return parts.join(" > ");
}

function getNthChildSegment(el: Element): string {
  const tag = el.tagName.toLowerCase();
  const parent = el.parentElement;
  if (!parent) return tag;

  // Use same-tag siblings to compute the position, and match via
  // :nth-of-type(N) — CSS evaluates :nth-of-type against same-tag siblings,
  // so the math matches whether the parent has mixed-tag children or not.
  // (Using :nth-child(N) here would be wrong for mixed-tag parents because
  // :nth-child counts ALL siblings, not just same-tag ones.)
  const siblings = Array.from(parent.children).filter(
    (c) => c.tagName === el.tagName,
  );
  if (siblings.length === 1) return tag;

  const index = siblings.indexOf(el) + 1;
  return `${tag}:nth-of-type(${index})`;
}
