/**
 * Metadata Generation Handler (Google Gemini)
 *
 * Generates meaningful titles, descriptions, and suggested tags from transcripts.
 * Only overwrites auto-generated or empty titles — preserves user-edited titles.
 */

import { getGoogleAI, GOOGLE_CONFIG } from '@/lib/google/client';
import { createClient as createAdminClient } from '@/lib/supabase/admin';
import { withAgentLogging, logAgentAction } from '@/lib/services/agent-logger';
import type { Database } from '@/lib/types/database';
import type { ProgressCallback } from '../job-processor';

type Job = Database['public']['Tables']['jobs']['Row'];

interface MetadataPayload {
  recordingId: string;
  transcriptId?: string;
  orgId: string;
}

interface GeneratedMetadata {
  title: string;
  description: string;
  tags: string[];
}

/** Matches auto-generated titles like "Recording 2026-02-11" or "Recording 2026-02-11 14:30" */
const AUTO_TITLE_PATTERN = /^Recording\s+\d{4}-\d{2}-\d{2}/i;

/** Returns true if the title is auto-generated or empty. */
function isAutoGeneratedTitle(title: string | null): boolean {
  if (!title || title.trim() === '') return true;
  if (title.toLowerCase() === 'untitled') return true;
  if (AUTO_TITLE_PATTERN.test(title)) return true;
  return false;
}

const METADATA_PROMPT = `You are a metadata extraction specialist. Analyze the following transcript and generate:

1. **title**: A concise, descriptive title (max 80 characters) that captures the specific topic discussed. Never use generic titles like "Screen Recording", "Meeting Notes", "Untitled", or "Recording Session". Instead, extract the actual subject matter.

2. **description**: A 1-2 sentence summary that describes the content and its key takeaways.

3. **tags**: Up to 5 lowercase tag names (single words or short phrases) that categorize the content by topic, technology, or domain.

Respond ONLY with valid JSON in this exact format (no markdown, no code fences):
{"title": "...", "description": "...", "tags": ["...", "..."]}`;

export async function handleGenerateMetadata(
  job: Job,
  progressCallback?: ProgressCallback
): Promise<void> {
  const payload = job.payload as unknown as MetadataPayload;
  const { recordingId, orgId } = payload;

  console.log(`[Metadata] Starting metadata generation for content ${recordingId}`);

  const supabase = createAdminClient();
  const loggingParams = {
    orgId,
    agentType: 'smart_processing',
    actionType: 'generate_metadata',
    contentId: recordingId,
    inputSummary: `Generate metadata for content ${recordingId}`,
  };

  progressCallback?.(10, 'Fetching transcript...');

  // Fetch transcript text by content_id
  const { data: transcript, error: transcriptError } = await supabase
    .from('transcripts')
    .select('text')
    .eq('content_id', recordingId)
    .single();

  if (transcriptError || !transcript) {
    console.warn(
      `[Metadata] No transcript found for content ${recordingId}, skipping metadata generation`
    );
    await logAgentAction({ ...loggingParams, outcome: 'skipped', outputSummary: 'No transcript found' });
    return;
  }

  const transcriptText = transcript.text || '';

  if (!transcriptText.trim()) {
    console.warn(
      `[Metadata] Transcript text is empty for content ${recordingId}, skipping`
    );
    await logAgentAction({ ...loggingParams, outcome: 'skipped', outputSummary: 'Transcript text is empty' });
    return;
  }

  progressCallback?.(20, 'Fetching current content...');

  // Fetch current content to check existing title/description
  const { data: content, error: contentError } = await supabase
    .from('content')
    .select('title, description')
    .eq('id', recordingId)
    .single();

  if (contentError || !content) {
    console.warn(
      `[Metadata] Content not found for id ${recordingId}, skipping`
    );
    await logAgentAction({ ...loggingParams, outcome: 'skipped', outputSummary: 'Content not found' });
    return;
  }

  // Transcript and content verified — wrap the Gemini call in agent logging
  await withAgentLogging(loggingParams, async () => {
    progressCallback?.(30, 'Generating metadata with Gemini...');

    const isShortTranscript = transcriptText.length < 50;

    // Truncate extremely long transcripts to stay within token budget
    const maxChars = 30000;
    const truncatedText =
      transcriptText.length > maxChars
        ? transcriptText.slice(0, maxChars) + '\n[...transcript truncated]'
        : transcriptText;

    const shortTranscriptNote = isShortTranscript
      ? '\n\nNote: This transcript is very short. Do your best to generate a title from the limited content available.'
      : '';

    const fullPrompt = `${METADATA_PROMPT}${shortTranscriptNote}\n\nTranscript:\n${truncatedText}`;

    const googleAI = getGoogleAI();
    const model = googleAI.getGenerativeModel({
      model: GOOGLE_CONFIG.DOCIFY_MODEL,
      generationConfig: {
        temperature: 0.3,
        maxOutputTokens: 512,
      },
    });

    const result = await model.generateContent(fullPrompt);
    const responseText = result.response.text();

    progressCallback?.(70, 'Parsing generated metadata...');

    const metadata = parseMetadataResponse(responseText);

    if (!metadata) {
      throw new Error('Failed to parse Gemini response as valid metadata JSON');
    }

    progressCallback?.(80, 'Updating content...');

    // Only overwrite auto-generated or empty fields
    const update: { title?: string; description?: string } = {};

    if (isAutoGeneratedTitle(content.title)) {
      update.title = metadata.title.slice(0, 80);
    }

    if (!content.description || content.description.trim() === '') {
      update.description = metadata.description;
    }

    if (Object.keys(update).length > 0) {
      const { error: updateError } = await supabase
        .from('content')
        .update(update)
        .eq('id', recordingId);

      if (updateError) {
        throw new Error(`Failed to update content metadata: ${updateError.message}`);
      }

      console.log(
        `[Metadata] Updated content ${recordingId}: ${Object.keys(update).join(', ')}`
      );
    } else {
      console.log(
        `[Metadata] Content ${recordingId} has user-edited title and description; skipping update`
      );
    }

    progressCallback?.(90, 'Storing suggested tags...');

    // Store suggested tags and generation results in job result
    const jobResult: Record<string, unknown> = {
      suggestedTags: metadata.tags,
      generatedTitle: metadata.title,
      generatedDescription: metadata.description,
      titleUpdated: 'title' in update,
      descriptionUpdated: 'description' in update,
    };

    if (isShortTranscript) {
      jobResult.lowConfidence = true;
      jobResult.reason = 'Transcript shorter than 50 characters';
    }

    await supabase
      .from('jobs')
      .update({ result: jobResult })
      .eq('id', job.id);

    progressCallback?.(100, 'Metadata generation complete');

    console.log(
      `[Metadata] Metadata generation complete for content ${recordingId} (tags: ${metadata.tags.join(', ')})`
    );
  });
}

/**
 * Parse the Gemini response into structured metadata.
 * Handles both clean JSON and JSON wrapped in markdown code fences.
 */
function parseMetadataResponse(responseText: string): GeneratedMetadata | null {
  try {
    // Strip markdown code fences if present
    let cleaned = responseText.trim();
    if (cleaned.startsWith('```')) {
      cleaned = cleaned.replace(/^```(?:json)?\s*\n?/, '').replace(/\n?```\s*$/, '');
    }

    const parsed = JSON.parse(cleaned);

    if (!parsed.title || typeof parsed.title !== 'string') return null;
    if (!parsed.description || typeof parsed.description !== 'string') return null;

    return {
      title: parsed.title.trim(),
      description: parsed.description.trim(),
      tags: Array.isArray(parsed.tags)
        ? parsed.tags
            .filter((t: unknown): t is string => typeof t === 'string')
            .map((t: string) => t.trim().toLowerCase())
            .slice(0, 5)
        : [],
    };
  } catch {
    return null;
  }
}
