-- TRIB-46: Seed vendor wiki pages for HubSpot, Jira, and Zendesk
-- Applied via mcp__supabase__apply_migration (name: trib_46_vendor_wiki_pages_hubspot_jira_zendesk)
-- 30 pages total (10 per app), matching detectScreen() output from context-engine.ts
--
-- HubSpot screens: contact-detail, contacts-list, company-detail, deal-detail,
--                  deals-board, ticket-detail, dashboard, workflows, email, forms
--
-- Jira screens:   issue-detail, board, backlog, roadmap, issue-list, dashboard,
--                  project-list, unknown-jira, unknown-jira-settings, unknown-jira-search
--
-- Zendesk screens: ticket-detail, tickets-list, user-detail, organization-detail,
--                   reports, views, admin, dashboard, unknown-zendesk, unknown-zendesk-macros

-- =========================================================================
-- HubSpot (10 pages)
-- =========================================================================

INSERT INTO vendor_wiki_pages (app, screen, content, element_selectors)
VALUES
(
  'hubspot',
  'contact-detail',
  E'---\nlayer: vendor\napp: hubspot\nscreen: contact-detail\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Contact Detail Page\n\n## Navigation\nAccessed via: Contacts > Contacts > [Contact Name]\n\n## Overview\nThe contact detail page is the central hub for managing an individual contact in HubSpot CRM. It displays all known information about a person, including their communication history, associated companies, deals, and tickets. The left column shows the contact''s properties (name, email, phone, lifecycle stage, lead status), while the middle column displays the activity timeline, and the right column shows associations and attachments.\n\n## Key Fields\n- **Email**: Primary identifier. Displayed prominently at the top. Click to send an email directly.\n- **Phone Number**: Click-to-call enabled if calling is configured.\n- **Lifecycle Stage**: Dropdown. Values: Subscriber, Lead, MQL, SQL, Opportunity, Customer, Evangelist, Other.\n- **Lead Status**: Dropdown. Values: New, Open, In Progress, Open Deal, Unqualified, Attempted to Contact, Connected.\n- **Contact Owner**: Dropdown to assign the contact to a team member.\n- **Last Activity Date**: Auto-populated timestamp of the most recent interaction.\n\n## Common Actions\n- **Create Task**: Opens a task creation panel in the right sidebar. Assign due date, type, and priority.\n- **Create Note**: Adds a note to the contact''s activity timeline. Supports @mentions for team members.\n- **Log Activity**: Log a call, email, or meeting manually. Includes outcome and duration fields.\n- **Send Email**: Opens the email composer with the contact pre-populated as the recipient.\n- **Make a Call**: Initiates a call through HubSpot''s calling tool (requires calling integration).\n- **Schedule Meeting**: Opens the meeting scheduler with the contact pre-filled.\n\n## Related Panels\n- **Activity Timeline**: Chronological log of all emails, calls, meetings, tasks, notes, and form submissions.\n- **Deals**: Associated deals with stage, amount, and close date.\n- **Companies**: Linked company records.\n- **Tickets**: Support tickets associated with this contact.\n- **Conversations**: Live chat and chatbot interactions.\n\n## UI Element Selectors\n- Lifecycle Stage dropdown: `[data-selenium-test="property-input-lifecyclestage"]`\n- Lead Status dropdown: `[data-selenium-test="property-input-hs_lead_status"]`\n- Email property: `[data-selenium-test="property-input-email"]`\n- Create Task button: `[data-selenium-test="timeline-create-task"]`\n- Activity timeline: `[data-selenium-test="timeline"]`',
  '{"Lifecycle Stage": "[data-selenium-test=\"property-input-lifecyclestage\"]", "Lead Status": "[data-selenium-test=\"property-input-hs_lead_status\"]", "Email Property": "[data-selenium-test=\"property-input-email\"]", "Create Task": "[data-selenium-test=\"timeline-create-task\"]", "Activity Timeline": "[data-selenium-test=\"timeline\"]"}'::jsonb
),
(
  'hubspot',
  'contacts-list',
  E'---\nlayer: vendor\napp: hubspot\nscreen: contacts-list\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Contacts List View\n\n## Navigation\nAccessed via: Contacts > Contacts (main navigation)\n\n## Overview\nThe contacts list view displays all contacts in a filterable, sortable table. Users can search, apply saved filters, create custom views, and perform bulk actions. The default view shows contact name, email, phone, contact owner, and last activity date. Columns are customizable per user.\n\n## Key Features\n- **Search Bar**: Full-text search across all contact properties. Located at the top of the table.\n- **Filters**: Click "Advanced filters" to build complex filter criteria using any contact property. Supports AND/OR logic.\n- **Saved Views**: Create and switch between saved filter configurations. Shared views are visible to the entire team.\n- **Column Customization**: Click "Edit columns" to add, remove, or reorder table columns.\n- **Pagination**: Navigate through pages of results. Default page size is 25 records.\n\n## Common Actions\n- **Create Contact**: Button in the top-right corner. Opens a modal to enter contact details.\n- **Import**: Import contacts from CSV, spreadsheet, or sync from another app.\n- **Export**: Download the current filtered view as a CSV file.\n- **Bulk Edit**: Select multiple contacts with checkboxes, then use the toolbar for bulk property updates, list enrollment, or deletion.\n- **Bulk Delete**: Select contacts and click "Delete" in the bulk action toolbar. Requires confirmation.\n\n## Table Interactions\n- **Sort**: Click any column header to sort ascending/descending.\n- **Inline Edit**: Some properties can be edited directly in the table by clicking the cell.\n- **Quick Preview**: Hover over a contact name to see a preview card with key details.\n\n## UI Element Selectors\n- Search input: `[data-selenium-test="object-filter-search-input"]`\n- Create contact button: `[data-selenium-test="contacts-create-button"]`\n- Advanced filters: `[data-selenium-test="filter-button"]`\n- Table rows: `[data-selenium-test="table-row"]`\n- Bulk action toolbar: `[data-selenium-test="bulk-action-toolbar"]`',
  '{"Search Input": "[data-selenium-test=\"object-filter-search-input\"]", "Create Contact": "[data-selenium-test=\"contacts-create-button\"]", "Advanced Filters": "[data-selenium-test=\"filter-button\"]", "Table Row": "[data-selenium-test=\"table-row\"]", "Bulk Actions": "[data-selenium-test=\"bulk-action-toolbar\"]"}'::jsonb
),
(
  'hubspot',
  'company-detail',
  E'---\nlayer: vendor\napp: hubspot\nscreen: company-detail\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Company Detail Page\n\n## Navigation\nAccessed via: Contacts > Companies > [Company Name]\n\n## Overview\nThe company detail page provides a comprehensive view of an organization in HubSpot CRM. It aggregates data from associated contacts, deals, and tickets to give a complete picture of the business relationship. The layout mirrors the contact detail page: properties on the left, activity timeline in the center, and associations on the right.\n\n## Key Fields\n- **Company Name**: Primary identifier displayed at the top of the page.\n- **Company Domain Name**: The company''s website domain. Used for automatic contact-company association.\n- **Industry**: Dropdown with standard industry categories.\n- **Annual Revenue**: Currency field representing the company''s yearly revenue.\n- **Number of Employees**: Numeric field. Can be a range or exact number.\n- **Company Owner**: Dropdown to assign a team member as the owner.\n- **Lifecycle Stage**: Tracks the company''s position in the sales pipeline.\n- **City / State / Country**: Location fields for the company''s primary address.\n\n## Common Actions\n- **Add Contact**: Associate an existing contact or create a new one linked to this company.\n- **Create Deal**: Open a new deal pre-associated with this company.\n- **Create Note**: Add a note to the company''s activity timeline.\n- **Log Activity**: Log a call, email, or meeting. Activity is shared across associated contacts.\n- **Create Task**: Create a follow-up task linked to the company.\n\n## Related Panels\n- **Contacts**: All contacts associated with this company. Shows name, email, and job title.\n- **Deals**: Active and closed deals. Shows stage, amount, and close date.\n- **Tickets**: Support tickets from contacts at this company.\n- **Activity Timeline**: Aggregated activity from the company and all associated contacts.\n\n## UI Element Selectors\n- Company Name header: `[data-selenium-test="record-title"]`\n- Industry property: `[data-selenium-test="property-input-industry"]`\n- Add Contact button: `[data-selenium-test="associations-add-button-contacts"]`\n- Company Owner: `[data-selenium-test="property-input-hubspot_owner_id"]`\n- Create Deal: `[data-selenium-test="associations-add-button-deals"]`',
  '{"Company Name": "[data-selenium-test=\"record-title\"]", "Industry": "[data-selenium-test=\"property-input-industry\"]", "Add Contact": "[data-selenium-test=\"associations-add-button-contacts\"]", "Company Owner": "[data-selenium-test=\"property-input-hubspot_owner_id\"]", "Create Deal": "[data-selenium-test=\"associations-add-button-deals\"]"}'::jsonb
),
(
  'hubspot',
  'deal-detail',
  E'---\nlayer: vendor\napp: hubspot\nscreen: deal-detail\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Deal Detail Page\n\n## Navigation\nAccessed via: Sales > Deals > [Deal Name] (from board or list view)\n\n## Overview\nThe deal detail page tracks a single sales opportunity through your pipeline. The top of the page shows a visual pipeline stage indicator, allowing you to advance or regress the deal by clicking on stages. Below that, the familiar three-column layout presents deal properties, the activity timeline, and associations.\n\n## Key Fields\n- **Deal Name**: Primary identifier for the opportunity.\n- **Pipeline**: Dropdown to select which sales pipeline this deal belongs to.\n- **Deal Stage**: Visual pipeline bar at the top. Click a stage to move the deal. Stages are configurable per pipeline.\n- **Amount**: Currency field for the deal value.\n- **Close Date**: Date picker. Drives forecasting reports.\n- **Deal Owner**: Dropdown to assign ownership.\n- **Deal Type**: Dropdown. Common values: New Business, Existing Business.\n- **Priority**: Dropdown. Values: Low, Medium, High.\n- **Forecast Category**: Auto-calculated or manually set. Values: Omit, Pipeline, Best Case, Commit, Closed.\n\n## Common Actions\n- **Move Stage**: Click a stage in the pipeline bar or use the "Move to" dropdown to advance the deal.\n- **Mark as Won**: Move to "Closed Won" stage. Triggers associated workflows and revenue tracking.\n- **Mark as Lost**: Move to "Closed Lost" stage. Prompts for a close-lost reason.\n- **Create Quote**: Generate a sales quote from the deal. Pre-populates with deal amount and line items.\n- **Add Line Items**: Open the line item editor to add products or services to the deal.\n- **Create Task**: Create a follow-up task associated with the deal.\n\n## Related Panels\n- **Contacts**: People involved in this deal.\n- **Companies**: Organizations associated with the deal.\n- **Line Items**: Products/services with quantities, pricing, and discounts.\n- **Quotes**: Generated quotes linked to this deal.\n- **Activity Timeline**: All interactions related to this deal.\n\n## UI Element Selectors\n- Pipeline stage bar: `[data-selenium-test="deal-stage-tracker"]`\n- Deal Amount: `[data-selenium-test="property-input-amount"]`\n- Close Date: `[data-selenium-test="property-input-closedate"]`\n- Deal Owner: `[data-selenium-test="property-input-hubspot_owner_id"]`\n- Create Quote: `[data-selenium-test="quote-create-button"]`',
  '{"Pipeline Stage Bar": "[data-selenium-test=\"deal-stage-tracker\"]", "Deal Amount": "[data-selenium-test=\"property-input-amount\"]", "Close Date": "[data-selenium-test=\"property-input-closedate\"]", "Deal Owner": "[data-selenium-test=\"property-input-hubspot_owner_id\"]", "Create Quote": "[data-selenium-test=\"quote-create-button\"]"}'::jsonb
),
(
  'hubspot',
  'deals-board',
  E'---\nlayer: vendor\napp: hubspot\nscreen: deals-board\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Deals Board View\n\n## Navigation\nAccessed via: Sales > Deals (default board view)\n\n## Overview\nThe deals board is a Kanban-style view of your sales pipeline. Each column represents a deal stage, and deal cards can be dragged between columns to update their stage. The board provides a visual overview of pipeline health, showing deal count and total value per stage at the top of each column.\n\n## Key Features\n- **Pipeline Selector**: Dropdown at the top to switch between different sales pipelines.\n- **Deal Cards**: Each card shows deal name, amount, close date, contact name, and deal owner avatar.\n- **Drag and Drop**: Move deal cards between columns to change their stage. The stage update is saved immediately.\n- **Column Summaries**: Each column header shows the count of deals and total weighted value.\n- **Sort Options**: Sort deals within a column by deal name, amount, close date, or last activity.\n\n## Common Actions\n- **Create Deal**: "+" button at the top of any column. Opens a quick-create panel pre-set to that stage.\n- **Filter Deals**: Use the filter bar to narrow by deal owner, close date range, amount range, or custom properties.\n- **Switch to List View**: Toggle between board and table view using the view switcher at the top.\n- **Edit Board Properties**: Customize which properties appear on deal cards.\n- **Bulk Actions**: Switch to list view for bulk operations (board view is single-deal interaction only).\n\n## Pipeline Management\n- **Add Stage**: Edit pipeline settings to add new stages. Stages have win probability percentages.\n- **Reorder Stages**: Drag stages in pipeline settings to change their order.\n- **Stage Automation**: Configure automated actions when deals enter or leave a stage.\n\n## UI Element Selectors\n- Pipeline selector: `[data-selenium-test="pipeline-select"]`\n- Deal card: `[data-selenium-test="deal-card"]`\n- Board column: `[data-selenium-test="board-column"]`\n- Create deal button: `[data-selenium-test="board-create-deal"]`\n- View toggle: `[data-selenium-test="view-toggle"]`',
  '{"Pipeline Selector": "[data-selenium-test=\"pipeline-select\"]", "Deal Card": "[data-selenium-test=\"deal-card\"]", "Board Column": "[data-selenium-test=\"board-column\"]", "Create Deal": "[data-selenium-test=\"board-create-deal\"]", "View Toggle": "[data-selenium-test=\"view-toggle\"]"}'::jsonb
),
(
  'hubspot',
  'ticket-detail',
  E'---\nlayer: vendor\napp: hubspot\nscreen: ticket-detail\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Ticket Detail Page\n\n## Navigation\nAccessed via: Service > Tickets > [Ticket Name]\n\n## Overview\nThe ticket detail page is the primary workspace for managing a support ticket in HubSpot Service Hub. It shows ticket properties, the conversation thread, and associations with contacts and companies. The ticket pipeline stage is displayed at the top, similar to the deal detail page.\n\n## Key Fields\n- **Ticket Name**: Short description of the issue.\n- **Ticket Status**: Pipeline stage indicator at the top. Common stages: New, Waiting on Contact, Waiting on Us, Closed.\n- **Priority**: Dropdown. Values: Low, Medium, High.\n- **Category**: Dropdown for ticket categorization (configurable).\n- **Source**: How the ticket was created (Email, Chat, Phone, Form, etc.).\n- **Ticket Owner**: Dropdown to assign the ticket to a support agent.\n- **Create Date**: Auto-set when the ticket is created.\n- **Close Date**: Auto-set when moved to a closed stage.\n\n## Common Actions\n- **Reply**: Send a response to the contact via email. The reply appears in the conversation thread.\n- **Add Note**: Internal note visible only to your team. Does not notify the contact.\n- **Change Status**: Click a stage in the pipeline bar or use the dropdown to update ticket status.\n- **Merge Tickets**: Combine duplicate tickets into a single record.\n- **Create Task**: Schedule a follow-up action for the ticket.\n- **Associate Contact**: Link the ticket to a specific contact or company.\n\n## Conversation Thread\n- **Email Thread**: Shows the full email conversation between the agent and contact.\n- **Internal Notes**: Yellow-highlighted notes only visible to the support team.\n- **Chat Transcripts**: If the ticket originated from live chat, the full transcript is embedded.\n\n## UI Element Selectors\n- Ticket status pipeline: `[data-selenium-test="ticket-stage-tracker"]`\n- Priority dropdown: `[data-selenium-test="property-input-hs_ticket_priority"]`\n- Reply editor: `[data-selenium-test="email-reply-editor"]`\n- Ticket Owner: `[data-selenium-test="property-input-hubspot_owner_id"]`\n- Conversation thread: `[data-selenium-test="conversation-thread"]`',
  '{"Ticket Status": "[data-selenium-test=\"ticket-stage-tracker\"]", "Priority": "[data-selenium-test=\"property-input-hs_ticket_priority\"]", "Reply Editor": "[data-selenium-test=\"email-reply-editor\"]", "Ticket Owner": "[data-selenium-test=\"property-input-hubspot_owner_id\"]", "Conversation Thread": "[data-selenium-test=\"conversation-thread\"]"}'::jsonb
),
(
  'hubspot',
  'dashboard',
  E'---\nlayer: vendor\napp: hubspot\nscreen: dashboard\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Reports Dashboard\n\n## Navigation\nAccessed via: Reporting > Dashboards\n\n## Overview\nThe reports dashboard displays a collection of report widgets arranged in a customizable grid layout. Dashboards provide at-a-glance visibility into sales performance, marketing metrics, service KPIs, or any combination. HubSpot includes several default dashboards (Sales, Marketing, Service) and allows users to create custom ones.\n\n## Key Features\n- **Dashboard Selector**: Dropdown at the top to switch between dashboards. Star a dashboard to set it as your default.\n- **Date Range Filter**: Global date range that applies to all reports on the dashboard. Supports preset ranges (This Month, Last Quarter) and custom date ranges.\n- **Report Widgets**: Individual report cards showing charts, tables, or single metrics. Each widget can be resized and repositioned.\n- **Frequency Filter**: Filter data by day, week, month, or quarter for time-series reports.\n\n## Common Actions\n- **Add Report**: Click "Add report" to add an existing report or create a new one directly on the dashboard.\n- **Create Dashboard**: "Create dashboard" button. Choose blank or from a template.\n- **Edit Layout**: Enter edit mode to drag, resize, and rearrange report widgets.\n- **Share Dashboard**: Send a dashboard link to teammates or set up recurring email delivery.\n- **Export**: Download dashboard as a PDF or image for stakeholder presentations.\n- **Clone Dashboard**: Duplicate an existing dashboard as a starting point for a new one.\n\n## Report Types\n- **Bar/Column Charts**: Compare metrics across categories or time periods.\n- **Line Charts**: Track trends over time (e.g., deals closed per month).\n- **Pie/Donut Charts**: Show proportional breakdowns.\n- **KPI Widgets**: Single-number metrics with trend indicators.\n- **Tables**: Detailed data grids with sorting and filtering.\n\n## UI Element Selectors\n- Dashboard selector: `[data-selenium-test="dashboard-selector"]`\n- Add report button: `[data-selenium-test="add-report-button"]`\n- Date range picker: `[data-selenium-test="date-range-picker"]`\n- Report widget: `[data-selenium-test="report-widget"]`\n- Edit layout button: `[data-selenium-test="edit-dashboard-button"]`',
  '{"Dashboard Selector": "[data-selenium-test=\"dashboard-selector\"]", "Add Report": "[data-selenium-test=\"add-report-button\"]", "Date Range": "[data-selenium-test=\"date-range-picker\"]", "Report Widget": "[data-selenium-test=\"report-widget\"]", "Edit Layout": "[data-selenium-test=\"edit-dashboard-button\"]"}'::jsonb
),
(
  'hubspot',
  'workflows',
  E'---\nlayer: vendor\napp: hubspot\nscreen: workflows\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Workflows\n\n## Navigation\nAccessed via: Automation > Workflows\n\n## Overview\nThe workflows screen is where you create and manage automated business processes in HubSpot. Workflows can trigger on contact, company, deal, ticket, or quote events and execute sequences of actions like sending emails, updating properties, creating tasks, or calling webhooks. The main view is a list of all workflows with status, enrollment count, and last edit date.\n\n## Key Features\n- **Workflow List**: Table showing all workflows with name, type, status (Active/Inactive), enrolled count, and last modified date.\n- **Folder Organization**: Organize workflows into folders for easier management.\n- **Search and Filter**: Search by name, filter by type (Contact, Company, Deal, Ticket, Custom Object), status, or folder.\n- **Performance Metrics**: Each workflow shows total enrollments, currently enrolled, and goal completion rate.\n\n## Common Actions\n- **Create Workflow**: Click "Create workflow" and choose a type. Options: Start from scratch or use a template.\n- **Clone Workflow**: Duplicate an existing workflow to use as a starting point.\n- **Toggle Active/Inactive**: Turn a workflow on or off without deleting it. Pausing stops new enrollments but lets in-progress ones complete.\n- **Edit Workflow**: Opens the visual workflow editor with drag-and-drop action blocks.\n- **View History**: See a log of all enrollments, completions, and errors for a workflow.\n- **Delete Workflow**: Permanently remove. Requires confirmation. Active workflows must be deactivated first.\n\n## Workflow Editor\n- **Trigger Block**: Defines when a contact/record enters the workflow (form submission, property change, list membership, etc.).\n- **Action Blocks**: Steps executed in sequence: send email, set property, create task, if/then branch, delay, webhook.\n- **If/Then Branches**: Conditional logic that splits the workflow path based on property values or behaviors.\n- **Goal Criteria**: Optional exit condition. Records that meet the goal are removed from the workflow.\n\n## UI Element Selectors\n- Create workflow button: `[data-selenium-test="create-workflow-button"]`\n- Workflow list table: `[data-selenium-test="workflows-table"]`\n- Search input: `[data-selenium-test="workflow-search-input"]`\n- Status toggle: `[data-selenium-test="workflow-status-toggle"]`\n- Filter dropdown: `[data-selenium-test="workflow-type-filter"]`',
  '{"Create Workflow": "[data-selenium-test=\"create-workflow-button\"]", "Workflow Table": "[data-selenium-test=\"workflows-table\"]", "Search Input": "[data-selenium-test=\"workflow-search-input\"]", "Status Toggle": "[data-selenium-test=\"workflow-status-toggle\"]", "Type Filter": "[data-selenium-test=\"workflow-type-filter\"]"}'::jsonb
),
(
  'hubspot',
  'email',
  E'---\nlayer: vendor\napp: hubspot\nscreen: email\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Email Marketing\n\n## Navigation\nAccessed via: Marketing > Email\n\n## Overview\nThe email screen is the hub for creating and managing marketing emails in HubSpot. It shows a list of all email campaigns with their status (Draft, Scheduled, Sent), send date, open rate, click rate, and unsubscribe count. From here you can create new emails, clone existing ones, or dive into performance analytics.\n\n## Key Features\n- **Email List**: Table of all marketing emails with name, type (Regular, Automated, A/B), status, and performance metrics.\n- **Tabs**: Switch between Regular, Automated, Blog/RSS, and All email types.\n- **Search and Filter**: Search by email name, filter by campaign, status, or type.\n- **Performance Overview**: Quick stats for each email: sent count, open rate, click rate, bounce rate.\n\n## Common Actions\n- **Create Email**: Click "Create email" to start a new email. Choose Regular, Automated, or A/B test.\n- **Edit Email**: Opens the drag-and-drop email editor with content blocks, design tools, and personalization tokens.\n- **Clone Email**: Duplicate an existing email to reuse as a template.\n- **Send/Schedule**: After editing, choose to send immediately or schedule for a future date/time.\n- **A/B Test**: Create two variants with different subject lines, content, or send times. HubSpot automatically picks the winner based on opens or clicks.\n- **Analyze**: Click into a sent email to view detailed analytics: delivery, engagement, clicks by link, device breakdown, and contact-level activity.\n\n## Email Editor\n- **Drag-and-Drop Blocks**: Text, image, button, divider, video, social sharing, and custom HTML modules.\n- **Personalization Tokens**: Insert contact properties (first name, company name) using tokens like `{{contact.firstname}}`.\n- **Preview and Test**: Preview in desktop/mobile views and send test emails before launching.\n- **Smart Content**: Show different content based on contact list membership, lifecycle stage, or device type.\n\n## UI Element Selectors\n- Create email button: `[data-selenium-test="create-email-button"]`\n- Email list table: `[data-selenium-test="email-table"]`\n- Search input: `[data-selenium-test="email-search-input"]`\n- Type tabs: `[data-selenium-test="email-type-tabs"]`\n- Send button: `[data-selenium-test="email-send-button"]`',
  '{"Create Email": "[data-selenium-test=\"create-email-button\"]", "Email Table": "[data-selenium-test=\"email-table\"]", "Search Input": "[data-selenium-test=\"email-search-input\"]", "Type Tabs": "[data-selenium-test=\"email-type-tabs\"]", "Send Button": "[data-selenium-test=\"email-send-button\"]"}'::jsonb
),
(
  'hubspot',
  'forms',
  E'---\nlayer: vendor\napp: hubspot\nscreen: forms\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# HubSpot: Forms\n\n## Navigation\nAccessed via: Marketing > Forms\n\n## Overview\nThe forms screen lists all HubSpot forms used for lead capture across your website, landing pages, and pop-ups. Forms collect contact information and feed data into the CRM, triggering workflows and list enrollments. The list view shows form name, type, submissions count, page views, and conversion rate.\n\n## Key Features\n- **Form List**: Table showing all forms with name, type (Embedded, Standalone, Pop-up), status, submissions, views, and conversion rate.\n- **Tabs**: Filter by form type: All Forms, Regular Forms, Pop-up Forms, and Non-HubSpot Forms (tracked external forms).\n- **Folder Organization**: Organize forms into folders for better management.\n- **Search**: Search forms by name.\n\n## Common Actions\n- **Create Form**: Click "Create form" to start building. Choose between Embedded Form, Standalone Page, Pop-up Form, or Dropdown Banner.\n- **Edit Form**: Opens the form editor where you add/remove fields, configure validation, and set up form submission actions.\n- **Clone Form**: Duplicate a form to use as a starting point for a new one.\n- **Embed Code**: Copy the form embed code to place on external websites.\n- **View Submissions**: Click into a form to see all submissions with contact details and submitted values.\n- **Delete Form**: Remove a form. Active forms on published pages will stop collecting data.\n\n## Form Editor\n- **Field Types**: Single-line text, multi-line text, dropdown, radio, checkbox, date picker, file upload, and more.\n- **Field Properties**: Set labels, placeholder text, help text, required/optional, default values, and validation rules.\n- **Progressive Profiling**: Automatically swap out fields that are already known for the contact, collecting new information with each visit.\n- **Form Options**: Thank-you message or redirect URL, notification emails, GDPR consent fields, and recaptcha.\n- **Styling**: Customize form appearance including colors, fonts, button text, and layout.\n\n## UI Element Selectors\n- Create form button: `[data-selenium-test="create-form-button"]`\n- Forms table: `.private-form__field`\n- Search input: `[data-selenium-test="forms-search-input"]`\n- Submission count: `[data-selenium-test="form-submissions-count"]`\n- Form type tabs: `[data-selenium-test="form-type-tabs"]`',
  '{"Create Form": "[data-selenium-test=\"create-form-button\"]", "Forms Table": ".private-form__field", "Search Input": "[data-selenium-test=\"forms-search-input\"]", "Submissions Count": "[data-selenium-test=\"form-submissions-count\"]", "Form Type Tabs": "[data-selenium-test=\"form-type-tabs\"]"}'::jsonb
)

ON CONFLICT (app, screen) DO UPDATE SET
  content = EXCLUDED.content,
  element_selectors = EXCLUDED.element_selectors,
  updated_at = now();

-- =========================================================================
-- Jira (10 pages)
-- =========================================================================

INSERT INTO vendor_wiki_pages (app, screen, content, element_selectors)
VALUES
(
  'jira',
  'issue-detail',
  E'---\nlayer: vendor\napp: jira\nscreen: issue-detail\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Issue Detail Page\n\n## Navigation\nAccessed via: Project > Board/Backlog > [Issue Key] (e.g., PROJ-123), or via /browse/PROJ-123\n\n## Overview\nThe issue detail page is the central workspace for viewing and managing a single Jira issue (story, task, bug, epic, or subtask). It displays the issue summary, description, status, assignee, and all metadata fields. The right sidebar shows the detail panel with status transitions, assignment, priority, labels, and sprint. Below the description, the activity section shows comments, history, and worklog entries.\n\n## Key Fields\n- **Summary**: The issue title displayed at the top of the page. Click to edit inline.\n- **Status**: Displayed as a colored badge. Click to transition (e.g., To Do > In Progress > Done).\n- **Assignee**: Avatar and name. Click to reassign. "Assign to me" shortcut available.\n- **Reporter**: The person who created the issue. Typically auto-set but editable.\n- **Priority**: Icon + label. Values: Highest, High, Medium, Low, Lowest.\n- **Type**: Issue type icon (Story, Bug, Task, Epic, Subtask). Set at creation, rarely changed.\n- **Sprint**: Which sprint the issue belongs to. Editable from the detail panel.\n- **Story Points / Estimate**: Numeric estimate field. Click to edit.\n- **Labels**: Tag-style labels for cross-cutting categorization.\n- **Fix Version**: Target release version.\n\n## Common Actions\n- **Transition Status**: Click the status badge to open the transition dropdown. Available transitions depend on the workflow.\n- **Add Comment**: Scroll to the activity section and type in the comment box. Supports @mentions, /commands, and rich formatting.\n- **Attach Files**: Drag and drop files onto the issue, or click the attachment icon.\n- **Link Issue**: Create relationships: blocks, is blocked by, relates to, duplicates, etc.\n- **Create Subtask**: Click "Create subtask" to break the issue into smaller work items.\n- **Log Work**: Record time spent on the issue for time tracking.\n- **Move Issue**: Transfer to a different project while preserving history.\n\n## Activity Section\n- **Comments**: Threaded discussion with @mentions and emoji reactions.\n- **History**: Audit log of all field changes with timestamps and authors.\n- **Worklog**: Time entries logged against the issue.\n\n## UI Element Selectors\n- Status badge: `[data-testid="issue.views.issue-base.foundation.status.status-field-wrapper"]`\n- Assignee field: `[data-testid="issue.views.issue-base.foundation.assignee.assignee-field"]`\n- Comment input: `[data-testid="issue.activity.comment"]`\n- Priority field: `[data-testid="issue.views.issue-base.foundation.priority.priority-field"]`\n- Summary heading: `[data-testid="issue.views.issue-base.foundation.summary.heading"]`',
  '{"Status Badge": "[data-testid=\"issue.views.issue-base.foundation.status.status-field-wrapper\"]", "Assignee": "[data-testid=\"issue.views.issue-base.foundation.assignee.assignee-field\"]", "Comment Input": "[data-testid=\"issue.activity.comment\"]", "Priority": "[data-testid=\"issue.views.issue-base.foundation.priority.priority-field\"]", "Summary": "[data-testid=\"issue.views.issue-base.foundation.summary.heading\"]"}'::jsonb
),
(
  'jira',
  'board',
  E'---\nlayer: vendor\napp: jira\nscreen: board\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Board View\n\n## Navigation\nAccessed via: Project > Board, or /jira/software/projects/[KEY]/boards/[ID]\n\n## Overview\nThe board view is a Kanban or Scrum board that visualizes issues as cards organized into columns representing workflow statuses. In Scrum projects, the board shows only the active sprint''s issues. In Kanban projects, it shows all issues within configured column constraints. Cards can be dragged between columns to transition their status.\n\n## Key Features\n- **Columns**: Each column maps to one or more workflow statuses (e.g., To Do, In Progress, In Review, Done). Column names and mappings are configurable in board settings.\n- **Issue Cards**: Cards display the issue key, summary, assignee avatar, priority icon, and story points. Card layout is customizable.\n- **Swimlanes**: Horizontal groupings that divide the board by assignee, epic, priority, or no grouping.\n- **WIP Limits**: Kanban boards can set maximum issue counts per column. Columns exceeding the limit are highlighted in red.\n- **Quick Filters**: Toggle buttons at the top to filter by label, assignee, issue type, or custom JQL.\n\n## Common Actions\n- **Drag and Drop**: Move an issue card between columns to change its status. This triggers workflow transitions.\n- **Create Issue**: Click "+" at the bottom of any column to create a new issue in that status.\n- **Open Issue**: Click an issue card to open the detail panel on the right side (or navigate to the full issue page).\n- **Sprint Actions** (Scrum only): "Complete Sprint" button finishes the current sprint and moves incomplete issues to the backlog or next sprint.\n- **Board Settings**: Configure columns, swimlanes, quick filters, card layout, and estimation settings.\n- **Filter by Assignee**: Click an avatar in the filter bar to show only that person''s issues.\n\n## Board Configuration\n- **Column Mapping**: Map workflow statuses to board columns. Multiple statuses can map to one column.\n- **Card Layout**: Choose which fields appear on issue cards (priority, labels, due date, etc.).\n- **Quick Filters**: Define JQL-based filter toggles for common views.\n\n## UI Element Selectors\n- Board container: `[data-testid="software-board.board"]`\n- Board column: `[data-testid="software-board.board-container.board.column-header"]`\n- Issue card: `[data-testid="software-board.board-container.board.card-container"]`\n- Quick filters: `[data-testid="software-board.header.quick-filters"]`\n- Create issue input: `[data-testid="software-board.board-container.board.card-list.card.create-issue"]`',
  '{"Board Container": "[data-testid=\"software-board.board\"]", "Column Header": "[data-testid=\"software-board.board-container.board.column-header\"]", "Issue Card": "[data-testid=\"software-board.board-container.board.card-container\"]", "Quick Filters": "[data-testid=\"software-board.header.quick-filters\"]", "Create Issue": "[data-testid=\"software-board.board-container.board.card-list.card.create-issue\"]"}'::jsonb
),
(
  'jira',
  'backlog',
  E'---\nlayer: vendor\napp: jira\nscreen: backlog\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Backlog View\n\n## Navigation\nAccessed via: Project > Backlog, or /jira/software/projects/[KEY]/backlog\n\n## Overview\nThe backlog view shows all issues in a project organized into sprints (for Scrum) or a prioritized list (for Kanban). The top section shows the active sprint, followed by future sprints, with the unassigned backlog at the bottom. Issues can be dragged between sprints or reordered within a sprint to set priority.\n\n## Key Features\n- **Sprint Sections**: Collapsible sections for each sprint showing sprint name, date range, issue count, and story point total.\n- **Backlog Section**: The bottom section holds unassigned issues not yet committed to a sprint.\n- **Issue Rows**: Each row shows issue key, type icon, summary, priority, assignee, story points, and status.\n- **Epic Panel**: Toggle the epic panel on the left to filter backlog by epic. Color-coded epic bars appear on issue rows.\n- **Estimation**: Inline story point editing by clicking the estimate badge on each issue row.\n\n## Common Actions\n- **Create Sprint**: Click "Create sprint" to add a new empty sprint section.\n- **Start Sprint**: Set the sprint goal, date range, and activate it. Moves to the board view.\n- **Drag to Sprint**: Drag issues from the backlog into a sprint section, or between sprints.\n- **Reorder**: Drag issues up/down within a sprint or backlog to set relative priority (top = highest).\n- **Create Issue**: Click "Create issue" at the bottom of any section to add a new issue inline.\n- **Right-Click Context Menu**: Access quick actions: assign, change priority, move to sprint, split issue, flag, or delete.\n- **Bulk Select**: Hold Shift or Cmd/Ctrl to select multiple issues, then drag or use context menu for bulk operations.\n\n## Sprint Planning\n- **Sprint Goal**: Text field describing what the sprint aims to achieve.\n- **Capacity**: Compare story point total against team velocity to avoid overcommitting.\n- **Scope Indicators**: Visual indicators show if a sprint is over or under capacity.\n\n## UI Element Selectors\n- Backlog container: `[data-testid="software-backlog.backlog-content"]`\n- Sprint header: `[data-testid="software-backlog.sprint-header"]`\n- Create sprint button: `[data-testid="software-backlog.create-sprint-button"]`\n- Issue row: `[data-testid="software-backlog.backlog-content.card"]`\n- Epic panel toggle: `[data-testid="software-backlog.epic-panel-toggle"]`',
  '{"Backlog Container": "[data-testid=\"software-backlog.backlog-content\"]", "Sprint Header": "[data-testid=\"software-backlog.sprint-header\"]", "Create Sprint": "[data-testid=\"software-backlog.create-sprint-button\"]", "Issue Row": "[data-testid=\"software-backlog.backlog-content.card\"]", "Epic Panel": "[data-testid=\"software-backlog.epic-panel-toggle\"]"}'::jsonb
),
(
  'jira',
  'roadmap',
  E'---\nlayer: vendor\napp: jira\nscreen: roadmap\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Roadmap (Timeline) View\n\n## Navigation\nAccessed via: Project > Timeline/Roadmap, or /jira/software/projects/[KEY]/roadmap\n\n## Overview\nThe roadmap view provides a Gantt-chart-style timeline of epics and their child issues. Epics are displayed as horizontal bars spanning their start and due dates, with child issues nested beneath. This view is ideal for long-term planning, tracking epic progress, and communicating delivery timelines to stakeholders.\n\n## Key Features\n- **Epic Bars**: Horizontal bars showing each epic''s date range. Bar color indicates the epic''s color label. Bar fill shows progress (percentage of child issues completed).\n- **Child Issues**: Expand an epic to see its child issues listed below with their own date ranges.\n- **Time Scale**: Toggle between weeks, months, and quarters using the zoom control at the top right.\n- **Today Marker**: Vertical line indicating the current date for quick orientation.\n- **Dependencies**: Lines connecting related epics or issues to visualize blocking relationships.\n\n## Common Actions\n- **Create Epic**: Click "+ Create epic" at the bottom of the list or click an empty area on the timeline.\n- **Create Child Issue**: Click "+" on an expanded epic row to add a child issue.\n- **Adjust Dates**: Drag the left or right edge of an epic bar to change start/due dates. Drag the entire bar to shift both dates.\n- **Set Dependencies**: Draw a line from one epic to another to create a dependency link.\n- **Filter**: Use the search and filter bar to narrow by status, assignee, label, or text.\n- **Share Roadmap**: Export or share a read-only link for stakeholders who don''t have Jira access.\n\n## Progress Tracking\n- **Epic Progress Bar**: Shows the percentage of child issues in "Done" status.\n- **Status Counts**: Hover over an epic to see the breakdown of To Do, In Progress, and Done issues.\n- **Overdue Indicators**: Epics past their due date with incomplete work are highlighted.\n\n## UI Element Selectors\n- Roadmap container: `[data-testid="roadmap.page"]`\n- Epic row: `[data-testid="roadmap.epic-row"]`\n- Create epic button: `[data-testid="roadmap.create-epic-button"]`\n- Time scale toggle: `[data-testid="roadmap.time-scale-toggle"]`\n- Filter bar: `[data-testid="roadmap.filter-bar"]`',
  '{"Roadmap Container": "[data-testid=\"roadmap.page\"]", "Epic Row": "[data-testid=\"roadmap.epic-row\"]", "Create Epic": "[data-testid=\"roadmap.create-epic-button\"]", "Time Scale": "[data-testid=\"roadmap.time-scale-toggle\"]", "Filter Bar": "[data-testid=\"roadmap.filter-bar\"]"}'::jsonb
),
(
  'jira',
  'issue-list',
  E'---\nlayer: vendor\napp: jira\nscreen: issue-list\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Issue List View\n\n## Navigation\nAccessed via: Project > List, or /jira/software/projects/[KEY]/list\n\n## Overview\nThe issue list view shows all project issues in a flat, sortable table format. Unlike the board view, it displays issues regardless of sprint assignment and provides more detail per row. This view is useful for triaging, bulk editing, and detailed filtering. It supports inline editing of most fields.\n\n## Key Features\n- **Table Columns**: Customizable columns including Key, Summary, Type, Status, Priority, Assignee, Reporter, Created, Updated, Story Points, Sprint, Labels, and Fix Version.\n- **Sorting**: Click any column header to sort ascending or descending. Multiple column sort is supported.\n- **Grouping**: Group issues by status, assignee, priority, sprint, or epic using the "Group by" dropdown.\n- **Inline Editing**: Click most fields directly in the table to edit them without opening the issue.\n- **JQL Filter Bar**: Write or modify JQL (Jira Query Language) queries to filter the issue list precisely.\n\n## Common Actions\n- **Create Issue**: Click "Create" button in the top bar to open the issue creation dialog.\n- **Bulk Change**: Select multiple issues with checkboxes, then use "Bulk change" to update status, assignee, priority, or other fields in batch.\n- **Export**: Export the filtered list to CSV or printable format.\n- **Save Filter**: Save the current JQL query as a named filter for reuse.\n- **Share View**: Copy a link to the current filtered view or share it with teammates.\n- **Column Configuration**: Click the column header dropdown to add, remove, or reorder columns.\n\n## Filtering\n- **Basic Filters**: Dropdowns for Type, Status, Assignee, and Label above the table.\n- **JQL Mode**: Toggle to advanced JQL for complex queries like `status changed FROM "In Progress" AFTER -7d`.\n- **Text Search**: Search within issue summaries and descriptions.\n\n## UI Element Selectors\n- List container: `[data-testid="list-view.container"]`\n- Issue row: `[data-testid="list-view.list-item"]`\n- Create button: `[data-testid="list-view.create-button"]`\n- Filter bar: `[data-testid="list-view.filter-bar"]`\n- Column header: `[data-testid="list-view.column-header"]`',
  '{"List Container": "[data-testid=\"list-view.container\"]", "Issue Row": "[data-testid=\"list-view.list-item\"]", "Create Button": "[data-testid=\"list-view.create-button\"]", "Filter Bar": "[data-testid=\"list-view.filter-bar\"]", "Column Header": "[data-testid=\"list-view.column-header\"]"}'::jsonb
),
(
  'jira',
  'dashboard',
  E'---\nlayer: vendor\napp: jira\nscreen: dashboard\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Dashboard\n\n## Navigation\nAccessed via: Dashboards (top navigation), or /jira/dashboards\n\n## Overview\nThe Jira dashboard is a customizable homepage that displays gadgets. Each user can create multiple dashboards and set one as their default. Dashboards support a two-column layout where gadgets can be arranged by dragging.\n\n## Common Gadgets\n- **Assigned to Me**: List of issues currently assigned to you, sorted by priority.\n- **Activity Stream**: Real-time feed of recent activity across projects.\n- **Filter Results**: Display issues matching a saved JQL filter as a table.\n- **Pie Chart**: Visual breakdown of issues by any field.\n- **Created vs Resolved**: Line chart comparing issue creation rate to resolution rate over time.\n- **Sprint Burndown**: Shows remaining work in the active sprint against the ideal burndown line.\n\n## Common Actions\n- **Add Gadget**: Click "Add gadget" to browse and add new gadgets to the dashboard.\n- **Edit Layout**: Enter edit mode to drag, resize, and configure gadgets.\n- **Create Dashboard**: Click "Create dashboard" and choose blank or copy from an existing one.\n- **Set as Default**: Star a dashboard to make it your landing page.\n- **Share Dashboard**: Configure visibility for teams, projects, or the whole org.\n\n## UI Element Selectors\n- Dashboard container: `#ak-main-content`\n- Add gadget button: `[data-testid="dashboard.add-gadget-button"]`\n- Gadget frame: `[data-testid="dashboard.gadget-frame"]`\n- Dashboard selector: `[data-testid="dashboard.dashboard-selector"]`\n- Edit layout button: `[data-testid="dashboard.edit-button"]`',
  '{"Dashboard Container": "#ak-main-content", "Add Gadget": "[data-testid=\"dashboard.add-gadget-button\"]", "Gadget Frame": "[data-testid=\"dashboard.gadget-frame\"]", "Dashboard Selector": "[data-testid=\"dashboard.dashboard-selector\"]", "Edit Layout": "[data-testid=\"dashboard.edit-button\"]"}'::jsonb
),
(
  'jira',
  'project-list',
  E'---\nlayer: vendor\napp: jira\nscreen: project-list\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Project List\n\n## Navigation\nAccessed via: Projects (top navigation), or /jira/projects\n\n## Overview\nThe project list page shows all Jira projects the current user has access to. Each project row displays the project name, key, type (Software, Service Management, Business), lead, and category.\n\n## Key Features\n- **Project Cards/List**: Toggle between card view and list view.\n- **Search**: Search projects by name or key.\n- **Starred Projects**: Star frequently used projects for quick access.\n- **Project Type Filter**: Filter by Software, Service Management, or Business project types.\n\n## Common Actions\n- **Open Project**: Click a project to navigate to its board view.\n- **Create Project**: Click "Create project" to start the project creation wizard.\n- **Star Project**: Click the star icon to pin a project to your sidebar.\n- **Project Settings**: Click the three-dot menu to access settings and permissions.\n\n## UI Element Selectors\n- Project list container: `[data-testid="project-list.container"]`\n- Project row: `[data-testid="project-list.project-row"]`\n- Create project button: `[data-testid="project-list.create-project-button"]`\n- Search input: `[data-testid="project-list.search-input"]`\n- Star button: `[data-testid="project-list.star-button"]`',
  '{"Project List": "[data-testid=\"project-list.container\"]", "Project Row": "[data-testid=\"project-list.project-row\"]", "Create Project": "[data-testid=\"project-list.create-project-button\"]", "Search Input": "[data-testid=\"project-list.search-input\"]", "Star Button": "[data-testid=\"project-list.star-button\"]"}'::jsonb
),
(
  'jira',
  'unknown-jira',
  E'---\nlayer: vendor\napp: jira\nscreen: unknown-jira\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: General Navigation\n\n## Overview\nThis page covers general Jira Cloud navigation and features that apply across multiple screens.\n\n## Global Navigation\n- **Top Bar**: Contains the Jira logo (home), Projects dropdown, Filters dropdown, Dashboards dropdown, People dropdown, Apps dropdown, Create button, and Search.\n- **Search**: Click the search icon or press `/` to open global search.\n- **Create Button**: Blue "Create" button in the top bar opens the issue creation dialog from anywhere.\n- **Notifications**: Bell icon shows recent notifications.\n\n## Sidebar Navigation\n- **Project Sidebar**: Board, Backlog, Roadmap/Timeline, List, Code, Deployments, Project Pages, and Project Settings.\n\n## Common Keyboard Shortcuts\n- **C**: Create new issue\n- **/** : Open global search\n- **G then B**: Go to board\n- **G then K**: Go to backlog\n- **J / K**: Navigate between issues\n- **E**: Edit issue\n- **M**: Assign to me\n\n## UI Element Selectors\n- Top navigation: `[data-ds--page-layout--slot="top-navigation"]`\n- Main content: `#ak-main-content`\n- Sidebar: `[data-ds--page-layout--slot="left-sidebar"]`\n- Create button: `[data-testid="navigation-apps-create-button"]`\n- Search: `[data-testid="navigation-apps-search-button"]`',
  '{"Top Navigation": "[data-ds--page-layout--slot=\"top-navigation\"]", "Main Content": "#ak-main-content", "Sidebar": "[data-ds--page-layout--slot=\"left-sidebar\"]", "Create Button": "[data-testid=\"navigation-apps-create-button\"]", "Search": "[data-testid=\"navigation-apps-search-button\"]"}'::jsonb
),
(
  'jira',
  'unknown-jira-settings',
  E'---\nlayer: vendor\napp: jira\nscreen: unknown-jira-settings\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Project Settings\n\n## Navigation\nAccessed via: Project > Project Settings (gear icon in sidebar)\n\n## Overview\nJira project settings control the configuration of an individual project, including its workflow, issue types, permissions, notifications, and integrations.\n\n## Settings Sections\n- **Details**: Project Name, Key, Lead, Category, Avatar.\n- **Issue Types**: Configure which issue types are available.\n- **Workflow**: View and edit the workflow (statuses and transitions).\n- **Permissions**: Controls who can create, edit, transition, assign, and delete issues.\n- **Notifications**: Configure which events trigger email notifications.\n\n## UI Element Selectors\n- Settings navigation: `[data-testid="project-settings.navigation"]`\n- Details form: `[data-testid="project-settings.details-form"]`\n- Issue types list: `[data-testid="project-settings.issue-types"]`\n- Workflow editor: `[data-testid="project-settings.workflow"]`\n- Permissions table: `[data-testid="project-settings.permissions"]`',
  '{"Settings Nav": "[data-testid=\"project-settings.navigation\"]", "Details Form": "[data-testid=\"project-settings.details-form\"]", "Issue Types": "[data-testid=\"project-settings.issue-types\"]", "Workflow Editor": "[data-testid=\"project-settings.workflow\"]", "Permissions": "[data-testid=\"project-settings.permissions\"]"}'::jsonb
),
(
  'jira',
  'unknown-jira-search',
  E'---\nlayer: vendor\napp: jira\nscreen: unknown-jira-search\nversion: "Cloud 2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Jira: Search & Filters\n\n## Navigation\nAccessed via: Filters (top navigation), or the global search bar\n\n## Overview\nJira''s search and filter system lets you find issues across all projects using basic text search or advanced JQL.\n\n## Search Modes\n- **Basic Search**: Text search with dropdown field filters.\n- **JQL**: `field operator value ORDER BY field ASC/DESC`\n\n## Common JQL Queries\n- `assignee = currentUser() AND status != Done`\n- `project = PROJ AND sprint in openSprints()`\n- `priority in (Highest, High) AND status != Done`\n\n## Common Actions\n- **Save Filter**: Save the current query as a reusable filter.\n- **Share Filter**: Set permissions to share with individuals or groups.\n- **Subscribe**: Get periodic email notifications when new issues match.\n- **Bulk Change**: Select multiple results and apply bulk changes.\n\n## UI Element Selectors\n- Search input: `[data-testid="search-dialog-input"]`\n- JQL editor: `[data-testid="jql-editor-input"]`\n- Filter results: `[data-testid="search-results-table"]`\n- Save filter button: `[data-testid="save-filter-button"]`\n- View switcher: `[data-testid="search-view-switcher"]`',
  '{"Search Input": "[data-testid=\"search-dialog-input\"]", "JQL Editor": "[data-testid=\"jql-editor-input\"]", "Results Table": "[data-testid=\"search-results-table\"]", "Save Filter": "[data-testid=\"save-filter-button\"]", "View Switcher": "[data-testid=\"search-view-switcher\"]"}'::jsonb
)

ON CONFLICT (app, screen) DO UPDATE SET
  content = EXCLUDED.content,
  element_selectors = EXCLUDED.element_selectors,
  updated_at = now();

-- =========================================================================
-- Zendesk (10 pages)
-- =========================================================================

INSERT INTO vendor_wiki_pages (app, screen, content, element_selectors)
VALUES
(
  'zendesk',
  'ticket-detail',
  E'---\nlayer: vendor\napp: zendesk\nscreen: ticket-detail\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: Ticket Detail Page\n\n## Navigation\nAccessed via: Views > [View Name] > [Ticket Subject], or /agent/tickets/[ID]\n\n## Overview\nThe ticket detail page is the primary workspace for support agents in Zendesk. It shows the full conversation between the requester and support team, along with ticket metadata, internal notes, and related information.\n\n## Key Fields\n- **Requester**: The person who submitted the ticket.\n- **Assignee**: The agent responsible for the ticket.\n- **Status**: Open, Pending, On-hold, Solved, Closed.\n- **Priority**: Low, Normal, High, Urgent.\n- **Type**: Question, Incident, Problem, Task.\n- **Tags**: Freeform tags for categorization.\n- **Group**: Which team/department the ticket is assigned to.\n\n## Common Actions\n- **Public Reply**: Send a response visible to the requester.\n- **Internal Note**: Add a note visible only to agents.\n- **Apply Macro**: Execute a predefined response template.\n- **Merge Tickets**: Combine duplicate tickets.\n- **Change Status**: Use the submit button (Submit as Open, Pending, Solved).\n\n## UI Element Selectors\n- Ticket status: `[data-test-id="ticket-status-select"]`\n- Assignee field: `[data-test-id="ticket-assignee-field"]`\n- Reply editor: `[data-test-id="omnicomposer-rich-text-container"]`\n- Submit button: `[data-test-id="submit-button"]`\n- Macro button: `[data-test-id="macro-button"]`',
  '{"Ticket Status": "[data-test-id=\"ticket-status-select\"]", "Assignee": "[data-test-id=\"ticket-assignee-field\"]", "Reply Editor": "[data-test-id=\"omnicomposer-rich-text-container\"]", "Submit Button": "[data-test-id=\"submit-button\"]", "Macro Button": "[data-test-id=\"macro-button\"]"}'::jsonb
),
(
  'zendesk',
  'tickets-list',
  E'---\nlayer: vendor\napp: zendesk\nscreen: tickets-list\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: Tickets List (Views)\n\n## Navigation\nAccessed via: Views (left sidebar) > [View Name], or /agent/tickets\n\n## Overview\nThe tickets list page displays tickets matching a view''s filter criteria. Views are saved ticket filters that help agents organize and prioritize their workload.\n\n## Key Features\n- **Views Sidebar**: Left panel listing all available views.\n- **Ticket Table**: Sortable columns (Subject, Requester, Group, Assignee, Status, Priority).\n- **Play Mode**: Automatically cycle through unresolved tickets.\n- **View Count**: Each view shows the number of matching tickets.\n\n## Common Actions\n- **Open Ticket**: Click any row to open the ticket detail page.\n- **Bulk Actions**: Select multiple tickets for bulk status, assignee, or tag updates.\n- **Edit View**: Modify filter conditions, columns, grouping, and sort order.\n- **Create View**: Build a custom view with conditions.\n\n## UI Element Selectors\n- Views sidebar: `[data-test-id="views-sidebar"]`\n- Ticket table: `[data-test-id="ticket-table"]`\n- Play button: `[data-test-id="play-button"]`\n- Bulk action toolbar: `[data-test-id="bulk-action-toolbar"]`\n- Add view button: `[data-test-id="add-view-button"]`',
  '{"Views Sidebar": "[data-test-id=\"views-sidebar\"]", "Ticket Table": "[data-test-id=\"ticket-table\"]", "Play Button": "[data-test-id=\"play-button\"]", "Bulk Actions": "[data-test-id=\"bulk-action-toolbar\"]", "Add View": "[data-test-id=\"add-view-button\"]"}'::jsonb
),
(
  'zendesk',
  'user-detail',
  E'---\nlayer: vendor\napp: zendesk\nscreen: user-detail\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: User Detail Page\n\n## Navigation\nAccessed via: Ticket > Requester Name (click), or /agent/users/[ID]\n\n## Overview\nThe user detail page shows all information about a Zendesk end-user or agent, including profile information, organization membership, recent tickets, and custom user fields.\n\n## Key Fields\n- **Name**: The user''s display name.\n- **Email**: Primary email address.\n- **Phone**: Phone number.\n- **Organization**: The company/organization the user belongs to.\n- **Role**: End-user, Agent, or Admin.\n- **Tags**: User-level tags.\n\n## Common Actions\n- **Edit Profile**: Click fields to edit inline.\n- **Add Organization**: Link the user to organizations.\n- **Merge Users**: Combine duplicate user profiles.\n- **Suspend User**: Temporarily block from submitting tickets.\n- **Delete User**: Permanently remove and anonymize data.\n\n## UI Element Selectors\n- User name: `[data-test-id="user-name"]`\n- Email field: `[data-test-id="user-email"]`\n- Organization link: `[data-test-id="user-organization"]`\n- Tickets tab: `[data-test-id="user-tickets-tab"]`\n- Edit button: `[data-test-id="user-edit-button"]`',
  '{"User Name": "[data-test-id=\"user-name\"]", "Email": "[data-test-id=\"user-email\"]", "Organization": "[data-test-id=\"user-organization\"]", "Tickets Tab": "[data-test-id=\"user-tickets-tab\"]", "Edit Button": "[data-test-id=\"user-edit-button\"]"}'::jsonb
),
(
  'zendesk',
  'organization-detail',
  E'---\nlayer: vendor\napp: zendesk\nscreen: organization-detail\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: Organization Detail Page\n\n## Navigation\nAccessed via: User Profile > Organization Name (click), or /agent/organizations/[ID]\n\n## Overview\nThe organization detail page provides a consolidated view of a company or group in Zendesk. Organizations group users together, enabling shared ticket visibility, routing rules, and SLA policies.\n\n## Key Fields\n- **Name**: The organization''s display name.\n- **Domains**: Email domains for automatic user association.\n- **Group**: Default ticket assignment group.\n- **Tags**: Organization-level tags inherited by tickets.\n- **Shared Tickets**: Toggle for cross-user ticket visibility.\n\n## Common Actions\n- **Edit Organization**: Click fields to edit inline.\n- **Add User**: Associate an existing user.\n- **Delete Organization**: Remove the org (users remain).\n- **Add Domain**: Add email domains for auto-association.\n\n## UI Element Selectors\n- Organization name: `[data-test-id="organization-name"]`\n- Domains field: `[data-test-id="organization-domains"]`\n- Users tab: `[data-test-id="organization-users-tab"]`\n- Tickets tab: `[data-test-id="organization-tickets-tab"]`\n- Tags field: `[data-test-id="organization-tags"]`',
  '{"Organization Name": "[data-test-id=\"organization-name\"]", "Domains": "[data-test-id=\"organization-domains\"]", "Users Tab": "[data-test-id=\"organization-users-tab\"]", "Tickets Tab": "[data-test-id=\"organization-tickets-tab\"]", "Tags": "[data-test-id=\"organization-tags\"]"}'::jsonb
),
(
  'zendesk',
  'reports',
  E'---\nlayer: vendor\napp: zendesk\nscreen: reports\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: Reports (Explore)\n\n## Navigation\nAccessed via: Reporting > Explore, or /agent/reports\n\n## Overview\nZendesk Explore is the built-in analytics and reporting tool. It provides pre-built dashboards and a query builder for custom reports covering ticket volume, response times, agent performance, and CSAT.\n\n## Pre-Built Dashboards\n- **Support Dashboard**: Ticket volume, status distribution, channel breakdown.\n- **Efficiency Dashboard**: First response time, resolution time, one-touch rate.\n- **Agent Activity**: Per-agent metrics and workload.\n- **SLA Dashboard**: Achievement rates and breach counts.\n- **Satisfaction Dashboard**: CSAT results and trends.\n\n## Common Actions\n- **View Dashboard**: Click a pre-built dashboard.\n- **Create Report**: Open the query builder.\n- **Schedule Report**: Set up recurring email delivery.\n- **Export**: Download as CSV, Excel, PDF, or image.\n\n## UI Element Selectors\n- Reports container: `[data-garden-version]`\n- Date range picker: `[data-test-id="date-range-picker"]`\n- Dashboard tab: `[data-test-id="explore-dashboard-tab"]`\n- Query builder: `[data-test-id="explore-query-builder"]`\n- Export button: `[data-test-id="explore-export-button"]`',
  '{"Reports Container": "[data-garden-version]", "Date Range": "[data-test-id=\"date-range-picker\"]", "Dashboard Tab": "[data-test-id=\"explore-dashboard-tab\"]", "Query Builder": "[data-test-id=\"explore-query-builder\"]", "Export": "[data-test-id=\"explore-export-button\"]"}'::jsonb
),
(
  'zendesk',
  'views',
  E'---\nlayer: vendor\napp: zendesk\nscreen: views\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: Views Management (Admin)\n\n## Navigation\nAccessed via: Admin > Workspaces > Agent tools > Views, or /agent/admin/views\n\n## Overview\nThe views management page is where admins create, edit, and organize ticket views. Views are saved ticket filters that appear in the agent sidebar.\n\n## Key Features\n- **Views List**: Shared Views and Personal Views sections.\n- **View Order**: Drag to reorder.\n- **Active/Inactive Toggle**: Hide views without deleting.\n- **View Limits**: Up to 12 shared views in the sidebar.\n\n## Common Actions\n- **Create View**: Add conditions, columns, and sorting.\n- **Edit View**: Modify conditions or formatting.\n- **Clone View**: Duplicate as starting point.\n- **Deactivate View**: Toggle inactive.\n- **Set Permissions**: Control which groups can see each view.\n\n## UI Element Selectors\n- Views admin container: `[data-test-id="views-admin-container"]`\n- Add view button: `[data-test-id="add-view-button"]`\n- View row: `[data-test-id="view-row"]`\n- Conditions editor: `[data-test-id="view-conditions-editor"]`\n- Columns editor: `[data-test-id="view-columns-editor"]`',
  '{"Views Container": "[data-test-id=\"views-admin-container\"]", "Add View": "[data-test-id=\"add-view-button\"]", "View Row": "[data-test-id=\"view-row\"]", "Conditions Editor": "[data-test-id=\"view-conditions-editor\"]", "Columns Editor": "[data-test-id=\"view-columns-editor\"]"}'::jsonb
),
(
  'zendesk',
  'admin',
  E'---\nlayer: vendor\napp: zendesk\nscreen: admin\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: Admin Center\n\n## Navigation\nAccessed via: Gear icon in sidebar, or /agent/admin\n\n## Overview\nThe Zendesk Admin Center is the central configuration hub covering account settings, agent management, channels, business rules, workspace customization, and integrations.\n\n## Admin Sections\n- **People**: Team members, groups, roles, user/org fields.\n- **Channels**: Email, Help Center, Chat, Talk, Social Messaging.\n- **Business Rules**: Triggers, automations, macros, SLAs.\n- **Workspaces**: Contextual workspaces, dynamic content, ticket forms.\n\n## Common Actions\n- **Add Agent**: People > Team Members > Add agent.\n- **Create Trigger**: Business Rules > Triggers > Add trigger.\n- **Configure SLA**: Business Rules > SLAs > Add policy.\n- **Set Up Channel**: Channels > select type > configure.\n- **Manage Apps**: Apps > Marketplace.\n\n## UI Element Selectors\n- Admin sidebar: `#main_navigation`\n- Admin content area: `.u-posAbsolute`\n- Settings section: `[data-test-id="admin-section"]`\n- Save button: `[data-test-id="admin-save-button"]`\n- Navigation link: `[data-test-id="admin-nav-link"]`',
  '{"Admin Sidebar": "#main_navigation", "Content Area": ".u-posAbsolute", "Settings Section": "[data-test-id=\"admin-section\"]", "Save Button": "[data-test-id=\"admin-save-button\"]", "Navigation Link": "[data-test-id=\"admin-nav-link\"]"}'::jsonb
),
(
  'zendesk',
  'dashboard',
  E'---\nlayer: vendor\napp: zendesk\nscreen: dashboard\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: Agent Dashboard\n\n## Navigation\nAccessed via: Home icon in sidebar (default landing page), or /agent/dashboard\n\n## Overview\nThe agent dashboard is the default landing page showing real-time workload overview and team activity. It displays ticket statistics, tickets requiring attention, satisfaction ratings, and recent activity.\n\n## Key Sections\n- **Ticket Statistics**: Good (within SLA), Bad (approaching/past SLA), Solved, Open counts.\n- **Requiring Attention**: Unread tickets, new replies, SLA-breaching tickets.\n- **Satisfaction**: CSAT score with Good/Bad breakdown.\n- **Recent Activity**: Feed of ticket updates and status changes.\n\n## Common Actions\n- **Open Ticket**: Click any ticket to go to detail page.\n- **Switch Views**: Navigate via sidebar.\n- **Check SLA**: Review "Bad" section for urgent tickets.\n- **Start Play Mode**: Cycle through tickets in a view.\n\n## UI Element Selectors\n- Dashboard container: `[data-test-id="agent-dashboard"]`\n- Ticket stats section: `[data-test-id="dashboard-ticket-stats"]`\n- Requiring attention list: `[data-test-id="dashboard-attention-list"]`\n- Satisfaction widget: `[data-test-id="dashboard-satisfaction"]`\n- Activity feed: `[data-test-id="dashboard-activity-feed"]`',
  '{"Dashboard Container": "[data-test-id=\"agent-dashboard\"]", "Ticket Stats": "[data-test-id=\"dashboard-ticket-stats\"]", "Attention List": "[data-test-id=\"dashboard-attention-list\"]", "Satisfaction": "[data-test-id=\"dashboard-satisfaction\"]", "Activity Feed": "[data-test-id=\"dashboard-activity-feed\"]"}'::jsonb
),
(
  'zendesk',
  'unknown-zendesk',
  E'---\nlayer: vendor\napp: zendesk\nscreen: unknown-zendesk\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: General Navigation\n\n## Overview\nGeneral Zendesk Support navigation covering the agent interface layout, global search, keyboard shortcuts, and tab-based multitasking.\n\n## Agent Interface Layout\n- **Top Bar**: Search, agent name/avatar, admin gear icon.\n- **Left Sidebar**: Home, Views, Reporting, Admin. Shows open ticket counts.\n- **Tabs Bar**: Open tickets as tabs for multitasking.\n- **Main Content Area**: Active view, ticket, or admin page.\n\n## Global Search\n- Press `Ctrl/Cmd + K` to open.\n- Search across tickets, users, organizations, and help center articles.\n- Use operators: `status:open`, `assignee:me`, `priority:high`.\n\n## Common Keyboard Shortcuts\n- **Ctrl/Cmd + K**: Open global search.\n- **Ctrl/Cmd + Alt + N**: Create new ticket.\n- **Tab + Return**: Submit ticket.\n- **Ctrl/Cmd + Shift + M**: Apply macro.\n\n## UI Element Selectors\n- Top navigation: `#main_navigation`\n- Search button: `[data-test-id="search-button"]`\n- Tabs bar: `[data-test-id="tabs-bar"]`\n- Sidebar views: `[data-test-id="sidebar-views"]`\n- Main content: `[data-garden-version]`',
  '{"Top Navigation": "#main_navigation", "Search Button": "[data-test-id=\"search-button\"]", "Tabs Bar": "[data-test-id=\"tabs-bar\"]", "Sidebar Views": "[data-test-id=\"sidebar-views\"]", "Main Content": "[data-garden-version]"}'::jsonb
),
(
  'zendesk',
  'unknown-zendesk-macros',
  E'---\nlayer: vendor\napp: zendesk\nscreen: unknown-zendesk-macros\nversion: "2026"\nlast_updated: 2026-04-11\nsource: "manual-mapping-v1"\n---\n\n# Zendesk: Macros & Triggers\n\n## Navigation\nAccessed via: Admin > Business Rules > Macros/Triggers\n\n## Overview\nMacros are agent-initiated templates. Triggers are event-driven automations that fire when tickets are created or updated.\n\n## Macros\n- Saved response templates applied manually to tickets.\n- Can set reply text, update fields, and add notes in one click.\n- Personal macros (agent-only) and shared macros (team-wide).\n\n## Triggers\n- Fire automatically on ticket create/update when conditions are met.\n- Execute actions like notifications, field changes, tags, webhooks.\n- Run in order; all matching triggers fire.\n\n## Common Actions\n- **Create Macro**: Admin > Macros > Add macro.\n- **Create Trigger**: Admin > Triggers > Add trigger.\n- **Organize**: Use categories and naming conventions.\n- **Reorder Triggers**: Order affects execution priority.\n\n## UI Element Selectors\n- Macros list: `[data-test-id="macros-list"]`\n- Add macro button: `[data-test-id="add-macro-button"]`\n- Triggers list: `[data-test-id="triggers-list"]`\n- Add trigger button: `[data-test-id="add-trigger-button"]`\n- Conditions editor: `[data-test-id="conditions-editor"]`',
  '{"Macros List": "[data-test-id=\"macros-list\"]", "Add Macro": "[data-test-id=\"add-macro-button\"]", "Triggers List": "[data-test-id=\"triggers-list\"]", "Add Trigger": "[data-test-id=\"add-trigger-button\"]", "Conditions Editor": "[data-test-id=\"conditions-editor\"]"}'::jsonb
)

ON CONFLICT (app, screen) DO UPDATE SET
  content = EXCLUDED.content,
  element_selectors = EXCLUDED.element_selectors,
  updated_at = now();
