-- Migration: Add RLS policies for transcripts, documents, and transcript_chunks
-- These tables need to be accessible to anon/authenticated roles since we use Clerk auth
-- Authorization is handled at the application layer via API routes

-- =============================================================================
-- TRANSCRIPTS TABLE
-- =============================================================================

-- Allow anon and authenticated users to read transcripts
-- Authorization is enforced in API routes via requireOrg()
CREATE POLICY "Allow read access to transcripts"
ON transcripts
FOR SELECT
TO anon, authenticated
USING (true);

-- Allow anon and authenticated users to update transcripts (for editing functionality)
-- Authorization is enforced in API routes via requireOrg()
CREATE POLICY "Allow update access to transcripts"
ON transcripts
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- INSERT and DELETE are restricted to service_role only (background jobs)
-- No additional policies needed - service_role already has full access

-- =============================================================================
-- DOCUMENTS TABLE
-- =============================================================================

-- Allow anon and authenticated users to read documents
-- Authorization is enforced in API routes via requireOrg()
CREATE POLICY "Allow read access to documents"
ON documents
FOR SELECT
TO anon, authenticated
USING (true);

-- Allow anon and authenticated users to update documents (for editing functionality)
-- Authorization is enforced in API routes via requireOrg()
CREATE POLICY "Allow update access to documents"
ON documents
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- INSERT and DELETE are restricted to service_role only (background jobs)
-- No additional policies needed - service_role already has full access

-- =============================================================================
-- TRANSCRIPT_CHUNKS TABLE
-- =============================================================================

-- Allow anon and authenticated users to read transcript chunks (for semantic search)
-- Authorization is enforced in API routes via requireOrg()
CREATE POLICY "Allow read access to transcript_chunks"
ON transcript_chunks
FOR SELECT
TO anon, authenticated
USING (true);

-- INSERT, UPDATE, and DELETE are restricted to service_role only (auto-generated by jobs)
-- No additional policies needed - service_role already has full access

-- =============================================================================
-- VERIFICATION
-- =============================================================================

-- Verify RLS is enabled on all three tables
DO $$
BEGIN
  IF NOT (SELECT relrowsecurity FROM pg_class WHERE relname = 'transcripts') THEN
    RAISE EXCEPTION 'RLS is not enabled on transcripts table';
  END IF;

  IF NOT (SELECT relrowsecurity FROM pg_class WHERE relname = 'documents') THEN
    RAISE EXCEPTION 'RLS is not enabled on documents table';
  END IF;

  IF NOT (SELECT relrowsecurity FROM pg_class WHERE relname = 'transcript_chunks') THEN
    RAISE EXCEPTION 'RLS is not enabled on transcript_chunks table';
  END IF;

  RAISE NOTICE 'RLS policies successfully created for transcripts, documents, and transcript_chunks';
END $$;
